global:
  scrape_interval: 15s  # How often to scrape metrics

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['host.docker.internal:5000']  # Replace with your Flask app's host and port